### ISSUE TITLE
Rework the entirety of the V8 version

### ISSUE THREAD

**Issue by hatf0** [hatf0/blocklandjs#13]
To-do: rework it, register our own class, etc.

**Comment by ohninedotseven** [comment]
V8 sucks. We're using SpiderMonkey now.

**Comment by ohninedotseven** [comment]
I lied. WIP.

**Comment by McTwist** [comment]
Jumping back and forth between several engines before you land on one that is so-so.

**Comment by hatf0** [comment]
Basically the entirety of the codebase is different from how it was originally. I'm considering this issue to be fixed.
