### ISSUE TITLE
js_exec does not work in v8

### ISSUE THREAD

**Issue by Anthonyrules144** [hatf0/blocklandjs#19]
V8 can't get the path to the file, as the working directory is not in the blockland directory at all.

**Comment by hatf0** [comment]
Make sure that your CWD is your Blockland folder. (verify this by doing `print(uv.misc.cwd());`)
If the CWD is not your blockland folder, do `uv.misc.chdir(“exact path to your blockland directory”);` and verify it by printing out the CWD.

**Comment by Anthonyrules144** [comment]
Working dir is set to blockland's directory, I did figure out though that js_exec doesn't work if the file has a number in it's name. Like _bob2.js_

**Comment by hatf0** [comment]
That’s odd. I’ll look into that. Thanks for the report.
