### ISSUE TITLE
Add setTimeout, clearTimeout, setInterval, and clearInterval

### ISSUE THREAD

**Issue by Electrk** [hatf0/blocklandjs#21]
`setTimeout` returns an ID that can be passed into `clearTimeout`
`setInterval` returns an ID that can be passed into `clearInterval`

Also, perhaps consider adding a `window` object?

**Comment by hatf0** [comment]
Okay, good lord. This has been implemented with the uv.timer class. To use,
```js
var a = new uv.timer();
a.start(500, 123, function(){print('test');}); //500 is the timeout, 123 is the repeat interval.
a.stop(); //To stop.
a.set_repeat(666); //This timer will now repeat every 666 ms..
```
