### ISSUE TITLE
Add support for serverCmds and clientCmds

### ISSUE THREAD

**Issue by Electrk** [hatf0/blocklandjs#22]

**Comment by hatf0** [comment]
Calling commandToClient/commandToServer requires to use of a constructed string. 
```js
var string = String.fromCharCode(0x01) + ts_func("getTag")("ourCmd");
```
Something along those lines
You must have whatever character 0x01 corresponds to as the first part of the string-- this is used in Torque internally to verify that it is a "tag" type.

**Comment by Electrk** [comment]
what about defining them?

**Comment by hatf0** [comment]
Defining client and server functions is pretty simple.
```js
function myClientCmdCallback() { print(arguments[0]); }
ts.expose(myClientCmdCallback, "", "clientCmdCallback");

function myServerCmdCallback() { print(arguments[0]);}
ts.expose(myServerCmdCallback, "", "serverCmdCallback");
```
