### ISSUE TITLE
Fix not getting method fields

### ISSUE THREAD

**Issue by McTwist** [hatf0/blocklandjs#26]
Currently getting static and dynamic fields works, but there's a third field called method fields. To get this one need to tag into the SimObject to get correct values:
https://github.com/hatf0/tge151/blob/9c6ff74f1949b3a2479e66577ae0acdf1b83d240/engine/console/consoleObject.h#L577
https://github.com/hatf0/tge151/blob/9c6ff74f1949b3a2479e66577ae0acdf1b83d240/engine/console/simBase.cc#L787
However, as FieldList is actually a template `Vector<T>`, it means it'll take much more work to make it attach to the engine properly.

**Comment by Visolator** [comment]
Yeah he is currently aware of the issue due to my attempts, but thank you for making a possible solution.

**Comment by McTwist** [comment]
I left it here for future reference as I didn't bother finding a possible fix for it. Will eventually pick it up in the future whenever we find an another way around it.

**Comment by hatf0** [comment]
One way to approach this is through the same approach that the DSO reader internally handles it.
https://github.com/hatf0/tge151/blob/master/engine/console/compiledEval.cc#L807
